### ISSUE TITLE
latLists or latList?

### ISSUE THREAD

**Issue by unitplane** [arcosin/Doric#4]
I haven't run this code yet but in the getData() methods you have a **latLists** empty list that you assign to data["lateral_states"] and a similar variable **latList** in the for loop. I'm not a Python dev but seems like these should be the same variable. Is this correct?

    latLists = []
    for lat in self.laterals:
        if lat is not None:   latList = [l.state_dict() for l in lat]
        else:                 latList.append(None)
    data["lateral_states"] = latLists
    return data

https://github.com/arcosin/Doric/blob/d1c0c3507127e31f52d2bf6afcce526e6756be1f/ProgBlocks.py#L341

**Comment by arcosin** [comment]
Good catch! Fixed now. Thanks!
