### ISSUE TITLE
save prognet

### ISSUE THREAD

**Issue by zyzhang1130** [arcosin/Doric#6]
Hi, it seems the standard way of saving model does not work on prognet. Is there any specific way of doing so?

Thanks.

**Comment by arcosin** [comment]
Saving should work as normal in pytorch, but loading might be a bit wonky. specifically, you might need to recreate all columns before loading. I will hopefully fix this eventually.

**Comment by zyzhang1130** [comment]
Yeah I tried save state dictionary it worked. Previously I tried to save the model itself. Thanks.
