### ISSUE TITLE
BackProp through Progressive nets

### ISSUE THREAD

**Issue by mbelalsh** [arcosin/Doric#7]
Hi, Thanks for putting in efforts to code the progressive nets. I have two questions:
1. I could not find the `backpropagation` method in the `ProgColumn` class.  Do you have any plans of implementing it? 
2.  In the manuscript (Adapters section), the authors talked about multiplying the lateral activations with a learned scalar alpha before feeding them to another neural network (e.g., MLP or CNN). I do see that you are passing the lateral connections to the neural network but I could not find the learned scalar `alpha ` anywhere.

**Comment by arcosin** [comment]
I'm glad you like it!

Regarding backpropagation, that is generally computed automatically by autograd in pytorch. As its a module, a column can be trained just like any other neural net in pytorch using autograd, but the whole Progressive net can as well if freezing is used correctly (freezing all previous columns before making a new one).

As for the adapters modification, we may add that in later. It hasn't been needed thus far. If you want to implement that as an option for your own uses on a fork and then create a pull request, that would be greatly appreciated :)

**Comment by mbelalsh** [comment]
Thanks for your response. If I have any plans of implementing it, I will let you know.
